name: sklearn-example
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - mlflow>=1.0
    - scipy
    - numpy>=1.14.3
    - pandas>=1.0.0
    - scikit-learn==0.19.1